name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set up Dart'
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: 'Install dependencies'
        run: flutter pub get

      - name: 'Publish to pub.dev'
        run: flutter pub publish --force