name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"

      - name: 'Install dependencies'
        run: flutter pub get

      - name: 'Publish to pub.dev'
        run: flutter pub publish --force